defaults:
  firstUser:
    username: 1111@server.com
    password: 1111

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/graph_ai
    username: postgres
    password: JustOleg1!

  jpa:
    show-sql: false
